if __name__ == "__main__":
    import subprocess
    from datetime import datetime as dt

    # requires : ./main has been built
    with open("README.md.template", "r") as f:
        readme = {"content": f.read()}

        def put(var, text):
            readme["content"] = readme["content"].replace("{{" + var + "}}", text)

        put("HELP", subprocess.check_output(["./main", "-h"], text=True))
        put("VERSION", subprocess.check_output(["./main", "-v"], text=True))
        put("DATE", str(dt.now()))
        put(
            "VERSION_NUM",
            subprocess.check_output(
                "ocaml -e '#use \"./lib/meta.ml\";; print_endline (Version.to_string get.version)'",
                shell=True,
                text=True,
            ),
        )
        with open("README.md", "w") as f:
            f.write(
                "<!-- THIS FILE IS GENERATED AUTOMATICALLY. -->\n<!-- DO NOT EDIT THIS FILE. -->\n<!-- EDIT README.md.template INSTEAD. -->\n"
                + readme["content"]
            )
