name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2.2.7
        with:
            ocaml-compiler: "5.1.1"
      - name: Set up Homebrew (MacOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
            NONINTERACTIVE=1 arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      - name: Set up Homebrew (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
            NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      - name: Install System Dependencies (MacOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: arch -x86_64 brew install llvm nasm
      - name: Install System Dependencies (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: brew install llvm nasm
      - name: Install OCaml Dependencies
        run: make deps
      - name: Build
        run: make build
      - name: Test
        run: make test
